name: Sok
version: ${project.version}
main: com.spectralmark.mcdev.sok.Sok
authors: [SpectralMark]
description: Crafting and Additions
commands:
  healme:
    description: Heal the User
    usage: /healme

